OneHotEncoding:

In [26]:
#Importing Libraries:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [27]:
#importing dataframe:
df=pd.read_csv('cars.csv')
df.head(2)

    brand  km_driven    fuel         owner  selling_price
0  Maruti     145500  Diesel   First Owner         450000
1   Skoda     120000  Diesel  Second Owner         370000

OneHotEncoding using Pandas:

In [28]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

OneHotEncoding using Sklearn:

In [29]:
#Train_test_split:

x=df.drop(columns=['selling_price'])
y=df['selling_price']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.head(1)

     brand  km_driven    fuel        owner
6518  Tata       2560  Petrol  First Owner

In [30]:
#defining column transformer:
col_tra=ColumnTransformer(transformers=[
    ('fuel',OneHotEncoder(drop='first',dtype=np.int32),['fuel']),
    ('owner',OneHotEncoder(drop='first',dtype=np.int32),['owner'])
],remainder='passthrough')
col_tra

ColumnTransformer(remainder='passthrough',
                  transformers=[('fuel',
                                 OneHotEncoder(drop='first',
                                               dtype=<class 'numpy.int32'>),
                                 ['fuel']),
                                ('owner',
                                 OneHotEncoder(drop='first',
                                               dtype=<class 'numpy.int32'>),
                                 ['owner'])])

In [31]:
#Fitting data
x_train=col_tra.fit_transform(x_train)
x_test=col_tra.transform(x_test)

In [32]:
x_train=pd.DataFrame(x_train, columns=col_tra.get_feature_names_out())
x_train.head()

,fuel__fuel_Diesel,fuel__fuel_LPG,fuel__fuel_Petrol,owner__owner_Fourth & Above Owner,owner__owner_Second Owner,owner__owner_Test Drive Car,owner__owner_Third Owner,remainder__brand,remainder__km_driven
0,0,0,1,0,0,0,0,Tata,2560
1,0,0,1,0,1,0,0,Honda,80000
2,1,0,0,1,0,0,0,Hyundai,150000
3,1,0,0,0,1,0,0,Maruti,120000
4,0,0,1,0,0,0,0,Maruti,25000